image: ghcr.io/scrtlabs/localsecret-gitpod:latest

tasks:
  - command: |
      node faucet_server.js
  - command: |
      ./bootstrap_init.sh

ports:
  - port: 26657
    onOpen: ignore
  - port: 9090-9091
  - port: 5000
