image: ghcr.io/scrtlabs/localsecret-gitpod:latest

tasks:
  - command: |
      node /home/gitpod/faucet_server.js
  - command: |
      /home/gitpod/bootstrap_init.sh false > /dev/null 2>&1 &

jetbrains:
  intellij:
    plugins:
      - io.digiline.secretideplugin
      - org.rust.lang
      - org.toml.lang

ports:
  - port: 26657
    onOpen: ignore
  - port: 9090-9091
  - port: 5000
  - port: 1317
    onOpen: ignore
